//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBH3aspmvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oderdetail
    {
        public int did { get; set; }
        public Nullable<int> oid { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<decimal> pprice { get; set; }
        public Nullable<int> pqty { get; set; }
        public Nullable<decimal> oamount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Price Price { get; set; }
    }
}
